version: "3.9"

services:
  pure-backend-practice:
    image: registry.hub.docker.com/purefuncinc/pure-backend-practice:0.0.1-SNAPSHOT
    environment:
      - TZ=Asia/Taipei
      - activeProfiles=docker
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - default

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=rootroot
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - default

  redis-exporter:
    image: bitnami/redis-exporter:latest
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=rootroot
    expose:
      - 9121
    ports:
      - "9121:9121"
    networks:
      - default

  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_PASSWORD=rootroot
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - default

  postgresql-exporter:
    image: bitnami/postgres-exporter:latest
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:rootroot@postgresql:5432/postgres?sslmode=disable
    expose:
      - 9187
    ports:
      - "9187:9187"
    networks:
      - default

#  mongodb:
#    image: mongo:6
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=rootroot
#    expose:
#      - 27017
#    ports:
#      - "27017:27017"
#    networks:
#      - default

  grafana:
    image: grafana/grafana:latest
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - default

  loki:
    image: grafana/loki:latest
    expose:
      - 3100
    ports:
      - "3100:3100"
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    expose:
      - 9090
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - default

networks:
  default:
