version: "3.9"

services:
    redis:
        image: redis:6
        expose:
            - 6379
        ports:
            - "6379:6379"
        networks:
            - default

    postgresql:
        image: postgres:13
        environment:
            - POSTGRES_PASSWORD=rootroot
        expose:
            - 5432
        ports:
            - "5432:5432"
        networks:
            - default

networks:
    default:
