name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -   name: Checkout
          uses: actions/checkout@v2
      -   name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: "11"
            distribution: "temurin"
            check-latest: true
      -   name: Gradle
          uses: gradle/gradle-build-action@v2
          env:
            GITHUB_REF_NAME: ${{ github.GITHUB_REF_NAME }}
            GITHUB_PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          with:
            arguments: clean build --scan -PexcludeTests=net/purefunc/voice/common/PrepareTestData.class,net/purefunc/voice/common/AnimalSimulation.class