name: Push

on:
  push:
    branches:
      - vincent

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -   name: Checkout
          uses: actions/checkout@v3
      -   name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: "11"
            distribution: "temurin"
            check-latest: true
      -   name: Maven
          env:
            GITHUB_PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          run: mvn clean package jib:build -DGITHUB_PUBLISH_TOKEN=$GITHUB_PUBLISH_TOKEN